### ISSUE TITLE
Extract correct information from bands

### ISSUE THREAD

**Issue by astrofrog** [glue-viz/glue-geospatial#1]
For instance band names, wavelengths, etc. At the moment the bands are just given the name 'Band ??'.

**Comment by robintw** [comment]
Unfortunately this is a right pain to deal with...as all sorts of different image formats implement this sort of metadata differently.

I'll see whether rasterio has a nice way of dealing with it, if not we might need to drop down to GDAL and write some code to try and choose the best bits of metadata we can find, falling back to the 'Band X' if needed.

Is there a way for each component of a dataset (not sure if I'm using the right terminology here...I need to read the docs a bit more and get it clear in my mind: basically here I mean a single band of a multi-band dataset) to have arbitrary bits of metadata attached to it, as well as a name? That could be really handy for doing wavelength plots: each band would have a name (eg. `Red`, `NIR`, `Blue`) and also a metadata value for wavelength in nm - allow users to choose bands by name, but plot with numerical values.

**Comment by astrofrog** [comment]
@robintw - you are using the right terminology! At the moment there is no metadata on components besides units. However, you could easily define a component sub-class to do this and then define how you want to store the wavelength information. I can provide an example if you like?

Just to check, could you clarify what you mean by 'plot with numerical values'?

**Comment by robintw** [comment]
Yeah, that sounds good.

In terms of a plot with numerical values, I mean something like:

[ACSpectraComparison_Rad_New.pdf](https://github.com/glue-viz/glue-geospatial/files/275072/ACSpectraComparison_Rad_New.pdf)

as opposed to:
[ACSpectraComparison_Rad.pdf](https://github.com/glue-viz/glue-geospatial/files/275073/ACSpectraComparison_Rad.pdf)

(Basically you have real physical values on the X axis, rather than 'band numbers' or textual descriptions such as 'Red', 'Green', 'Blue')

**Comment by robintw** [comment]
(Sorry, I had expected Github to show those inline - I should have converted to PNG before upload!)

**Comment by robintw** [comment]
Is there an easy way to give components multiple names? I suspect the answer is no...but ideally I'd like to be able to have what we have at the moment (Band 0, Band 1 etc), and the names/wavelengths of the bands given in the file (if present) - but with the user being able to view both fairly easily (sometimes it is important to be able to select Band 7 without knowing what wavelength it is or what its name is).

Is this a complex and bad idea...?

**Comment by astrofrog** [comment]
@robintw - multiple names/aliases aren't possible at the moment, but what about creating a composite component name such as `Band 1 - 340nm` if additional information is required? (just trying to understand the requirements before we consider refactoring how component labels are defined)

**Comment by robintw** [comment]
Fixed in 717f782f3cd4f8b2557e5f5caf487f591b6a2f97 (including starting band names at 1 - hope that's ok)
