### ISSUE TITLE
Image Viewer showing old resampled data when zooming/moving

### ISSUE THREAD

**Issue by robintw** [glue-viz/glue-geospatial#11]
I've found a strange graphical error when moving around images in the Image Viewer. Sometimes when zooming (or panning), you can still see the low-resolution resampled image around the edges of the display. For example:

<img width="586" alt="screen shot 2016-05-21 at 19 49 42" src="https://cloud.githubusercontent.com/assets/296686/15450202/99eeba0a-1f8d-11e6-830d-8a8865d99b63.png">

If you pan the window slightly it seems to update and display properly, but then if you zoom again it happens again.

Any thoughts?

**Comment by astrofrog** [comment]
Yes, there is a layer called `modest_image` which deals with the resampling on-the-fly. I think it's somehow not getting refreshed as soon as a zoom event happens. I can take a look to see if there is an obvious fix.

**Comment by robintw** [comment]
Fixed by glue-viz/glue#1000
